---
title: Homework 5 - Coding a navigation system
author: default author
date: last-modified
format:
  html:
    embed-resources: true
    theme: cosmo
---

* [LINK to GITHUB](https://github.com/cmsc-vcu/cmsc475-sp2024-hw5-template)
* [LINK to FIGMA PROTOTYPE CODE](https://www.figma.com/file/aSqekRNJn6DM1VMivvoibQ/Storyboard-Creator---Public-Demo-(Community)?type=design&node-id=111%3A2028&mode=design&t=PGNCnlkYRkizaQuu-1)

(this is the sample document.  You need to make it your own.)

(Your report should follow the outline below, found under the easter eggs.)

# xIntroduction

- Explain the purpose of the navigation strategy.
- Briefly describe the story told in five (or more) panels.

# xNavigation Goals

- State what you want users to achieve by navigating through the panels.
- Highlight the key points or emotions to convey.

# xNavigation Elements

- Explain how users will move from one panel to another.
- Mention if there are buttons, arrows, or gestures involved.

# xFigma mockup

- Add the figma mockup in an iframe.
- Explain how to use it in this section.

```{=html}
<center>
<iframe
src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FQJss2lSSmmUMKkKodCWxN2%2FHomework-4---Prototype%3Ftype%3Ddesign%26t%3DnIV2fhIRzGgxc44k-1%26scaling%3Dscale-down%26page-id%3D0%253A1%26node-id%3D3-2%26starting-point-node-id%3D3%253A2%26mode%3Ddesign"
style="border: 1px solid rgba(0, 0, 0, 0.1);"
width="800" height="450"  
data-external="1"
allowfullscreen
></iframe>
</center>
```

# xUser Testing

- Share your design with someone else.
- Explain your user testing procedure.  What did you ask?  What did they say?
- Consider their feedback and make adjustments as needed.

# xImplementation

Drop the appropriate link in the SRC field below.  

BE SURE to change the ./sketches/. to ./full/. so your script shows full screen and not in the editor.

```{=html}
<center>
<iframe
src="https://editor.p5js.org/jleonard99/full/5ujbqRESJ"
style="border: 1px solid rgba(0, 0, 0, 0.1);"
width="800"
height="450"  
data-external="1"
allowfullscreen="allowfullscreen"
webkitallowfullscreen="webkitallowfullscreen"
mozallowfullscreen="mozallowfullscreen"
allow="geolocation *; microphone *; camera *; midi *; encrypted-media *; autoplay *; clipboard-write *; display-capture *"
></iframe>
</center>
```

# xReflection

* This is the most important section of the assignment!
* Stop, Pause, Breath, and Consider.

1. How much time did you spend on the assignment?
1. What activities consumed the most of your time? 
1. How could you have been better prepared to tackle this assignment (in terms of skills or knowledge)?
1. What did you find most satisfying about this assignment?
1. What did you find most difficult about this assignment? 
1. Given more time, what would you do differently?

